### ISSUE TITLE
Segmentation fault and high load CPU

### ISSUE THREAD

**Issue by mrwert** [wangzhione/libiop#2]
Hello.
If the connection was **x** > **INT_POLL** (1024).

**Comment by wangzhione** [comment]
hi
在 linux 上有 epoll 管理可以忽略 INT_POLL.
在 winds 上可以看 WinSock2.h 文件中说明.

/*
 * Select uses arrays of SOCKETs.  These macros manipulate such
 * arrays.  FD_SETSIZE may be defined by the user before including
 * this file, but the default here should be >= 64.
 *
 * CAVEAT IMPLEMENTOR and USER: THESE MACROS AND TYPES MUST BE
 * INCLUDED IN WINSOCK2.H EXACTLY AS SHOWN HERE.
 */
#ifndef FD_SETSIZE
#define FD_SETSIZE      64
#endif /* FD_SETSIZE */

这里有个坑就是 epoll event 大小和 iop 对象为了省略一个宏都用了 INT_POLL. 
库的定位就是学习 : )

**Comment by mrwert** [comment]
hm hm :)
I thought that the counter resets the value to zero when the x > max.
I created 1000 connections and disconnected. I also wanted to add 100 connections - it did not work, the counter did not go to 0

**Comment by wangzhione** [comment]
非常感谢. 已经修复, 原因是我在 iop_delete list 结点没有调整.

**Comment by mrwert** [comment]
你好 :)
Thanks for the answer and for trying to fix, but
my server socket stops responding when n > INT_IOP (for example == **12**).
...
echo_connect base = 0x55821d2fd640, id : 1, arg = (nil)
echo_destroy base = 0x55821d2fd640, id : 1, arg = (nil)
echo_connect base = 0x55821d2fd640, id : 2, arg = (nil)
echo_connect base = 0x55821d2fd640, id : 3, arg = (nil)
echo_connect base = 0x55821d2fd640, id : 4, arg = (nil)
echo_connect base = 0x55821d2fd640, id : 5, arg = (nil)
echo_destroy base = 0x55821d2fd640, id : 5, arg = (nil)
echo_destroy base = 0x55821d2fd640, id : 4, arg = (nil)
echo_connect base = 0x55821d2fd640, id : 6, arg = (nil)
echo_destroy base = 0x55821d2fd640, id : 2, arg = (nil)
echo_connect base = 0x55821d2fd640, id : 7, arg = (nil)
echo_connect base = 0x55821d2fd640, id : 8, arg = (nil)
echo_destroy base = 0x55821d2fd640, id : 6, arg = (nil)
echo_connect base = 0x55821d2fd640, id : 9, arg = (nil)
echo_destroy base = 0x55821d2fd640, id : 8, arg = (nil)
echo_destroy base = 0x55821d2fd640, id : 9, arg = (nil)
echo_connect base = 0x55821d2fd640, id : 10, arg = (nil)
echo_destroy base = 0x55821d2fd640, id : 7, arg = (nil)
echo_connect base = 0x55821d2fd640, id : 11, arg = (nil)
echo_destroy base = 0x55821d2fd640, id : 10, arg = (nil)
echo_connect base = 0x55821d2fd640, id : 10, arg = (nil)
[src/iop.c:iop_add:162][0:Success]iop_get base is error = 0x55821d2fd640
[src/iop_server.c:iops_listen:108][9:Bad file descriptor]iop_add EV_READ timeout = 2, r = 4294967295
echo_destroy base = 0x55821d2fd640, id : 10, arg = (nil)
echo_destroy base = 0x55821d2fd640, id : 11, arg = (nil)
echo_destroy base = 0x55821d2fd640, id : 3, arg = (nil)
...

**Comment by mrwert** [comment]
And in the select method will be high load CPU. (Linux 4.15.0-33-generic #36-Ubuntu SMP).
and rename `base->iops` to `base->ios`
https://github.com/wangzhione/libiop/blob/master/libiop/iop/iop_poll%24select.h#L90

**Comment by wangzhione** [comment]
收到感谢, 正在跟踪问题, 修复问题

**Comment by wangzhione** [comment]
hi. 已经尝试 trying fix.
思路是最大并发处理 INT_IOP 条链接.

: ) 感谢 ~

**Comment by mrwert** [comment]
谢谢 ！
It's working stable!!!
